name: plotly_dash
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ansi2html=1.5.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - chart-studio=1.1.0
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - dash=1.19.0
  - dash-core-components=1.3.1
  - dash-html-components=1.0.1
  - dash-renderer=1.1.2
  - dash-table=4.4.1
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - flask=2.0.3
  - flask-compress=1.5.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - future=0.18.2
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter-dash=0.4.1
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.11
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openpyxl=3.0.5
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - pywin32=302
  - pywinpty=2.0.2
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - requests=2.27.1
  - retrying=1.3.3
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.0
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2021e
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
prefix: C:\Users\rolfc\miniconda3\envs\plotly_dash
