name: plotly_dash
channels:
  - defaults
dependencies:
  - python
  - ipykernel
  - seaborn
  - pandas
  - matplotlib
  - numpy
  - plotly
  - jupyter-dash
  - dash
  - chart-studio
  - nbformat
  - ipywidgets
  - openpyxl
  - jupyter_server_proxy
prefix: C:\Users\rolfc\miniconda3\envs\plotly_dash
